version: 0.0.1
image_acquisition:
  image_save_dir: 'images'
  camera:
    AcquisitionFrameRate: 30
    ExposureTime: 200
    OffsetX: 968
    OffsetY: 768
    Width: 512
    Height: 512
    PixelFormat: 'Mono8'
